// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6

package handler

import (
	"net/http"

	"wallet/api/server/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 链列表
				Method:  http.MethodPost,
				Path:    "/blockchain/list",
				Handler: BlockChainListHandler(serverCtx),
			},
			{
				// 创建钱包
				Method:  http.MethodPost,
				Path:    "/create/wallet",
				Handler: CreateWalletHandler(serverCtx),
			},
			{
				// 导入钱包
				Method:  http.MethodPost,
				Path:    "/import/wallet",
				Handler: ImportWalletHandler(serverCtx),
			},
			{
				// 代币转账
				Method:  http.MethodPost,
				Path:    "/wallet/defi/transfer",
				Handler: WalletDefiTransferHandler(serverCtx),
			},
			{
				// 查询钱包信息
				Method:  http.MethodPost,
				Path:    "/wallet/info",
				Handler: WalletInfoHandler(serverCtx),
			},
			{
				// 查询钱包交易记录
				Method:  http.MethodPost,
				Path:    "/wallet/transaction",
				Handler: WalletTransactionHandler(serverCtx),
			},
			{
				// 交易详情
				Method:  http.MethodPost,
				Path:    "/wallet/transaction/detail",
				Handler: WalletTransactionDetailHandler(serverCtx),
			},
			{
				// 转账
				Method:  http.MethodPost,
				Path:    "/wallet/transfer",
				Handler: WalletTransferHandler(serverCtx),
			},
		},
	)
}
